
*****t* PRICIPAL / TABLAS
*  TABLA
*    SECTOR.DBF => 11 : Sector al que correspode un cargo
*	[CODIGO,NOMBRE]
*    CARGO.DBF => 12 : Cargo de los empleados
*	[A,B,DEPTO]
*    DAT_EMPL.DBF => 1
*
*    ITEM1.DBF,TEMP_EVE.DBF => 2
*
*    MESES.DBF => 10
*
*    NIVEL.DBF => 13
*
*    BONOS.DBF => 14
*
*    HRS_EME.DBF => 16
*
*    BOMBOM.DBF => 18
*
*    PRESTAMO.DBF => 21
*
*    IVA.DBF => 22
*
*    PERSONAL.DBF => 32
*
*    VACACION.DBF => 38
*
*    REGIONAL.DBF => 40
*
*    TEMP_BOM.DBF => 42
*
*    TEMP_RAD.DBF => 43
*
*    acreedor.DBF => 48
*
*    TOTAL.DBF => 50
*
*    PRESTA.DBF => 91
*
*    temp_pres.DBF => 99
*
******

